export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_FAILURE = "FETCH_FAILURE";
export const FETCH_REQUEST = "FETCH_REQUEST";
export const REMOVE_ELEMENTS = "REMOVE_ELEMENTS";
export const EDIT_ELEMENT = "EDIT_ELEMENT";
export const ADD_NEW_ELEMENT = "ADD_NEW_ELEMENT";
